export enum WorkOrderStatus {
  Pending = 'pending',
  InProgress = 'in-progress',
  Completed = 'completed',
  Cancelled = 'cancelled',
  OnHold = 'on-hold'
} 


/* 
UPDATED ALREADY "UDIS PROBLEM
READY FOR COMPLETE CERTIFICATE WITH REQUIRMENT
READY FOR UPDATING " UDIS PROBLEM "
UPDATED ALREADY " NEED RTI ONLY
Under checking and Signatures by Inspectors
PAID WITH VAT 15%
UPDATED ALREADY "RTI & RECEIVING IN PROCESS
NEED D.P
READY FOR CHECKING " NEED TO PREPARE THE FILE AND  THE DOCUMENTS"
UPDATED ALREADY "ENG SECTION  FOR APPROVAL
Waiting shutdown
In Progress for permission
CANCEL WORK ORDER
NEED  REPLACMENT EQUIPMENT
3-WAITING FINANCIAL
READY FOR CHECKING
IN PROGRESS
CLOSED WITH MUSTAKHLAS NEED 1ST APPROVAL
NEED MUSTAKHLAS  WITHOUT REQUIRMENTS
UPDATED ALREADY "  NEED RECEIVING MATERIALS ONLY
COMPLETE CERTIFICATE NEED 2ND APPROVAL
CLOSED WITH MUSTAKHLAS NEED 2ND APPROVAL
MATERIALS RECEIVED  : NEED  155
READY FOR COMPLETE CERTIFICATE WITHOUT REQUIRMENT
CLOSED WITH MUSTAKHLAS NEED 1ST APPROVAL  NEED TO RETURN SCRAP


*/